baseurl         = "/"
theme           = "paper-now"
languageCode    = "en-us"
title           = "Site Title | Hugo Paper-Now"
canonifyurls    = true

[params]
  googleAnalytics   = ""
  pageNotFoundTitle = "404 - Page not found"
  
  articleTitle= "ENGR 001 Work Term Report"
  publishDate = "2016-12-18"
  doi         = ""
  github      = ""

[[params.authors]]
    id    = "David-li"
    name  = "David Li"
    email = "studentdavidli@gmail.com"
    url   = "https://web.uvic.ca/~lidavid/"
    orcid = "0000-0002-9298-3168"


[[params.affiliations]]
    name       = "University of Victoria"
    department = "Department of Computer Engineering"
    location   = "Victoria,BC, Canada"
    url        = "www.uvic.ca"
    members    = ["david-li"]

[[params.affiliations]]
    name       = "Harvard University"
    department = "Department of Molecular and Cellular Biology"
    location   = "Cambridge, MA, USA"
    url        = ""
    members    = ["alice-exemplar"]

[[params.affiliations]]
    name       = "Institut Teknologi Bandung"
    department = "School of Electrical Engineering and Informatics"
    location   = "Bandung, Indonesia"
    url        = "https://stei.itb.ac.id/id/"
    members    = ["em-exemplar"]

[[params.funders]]
    name   = "Medical Research Council"
    url    = ""
    sameAs = "http://doi.org/10.13039/501100000265"
    [[params.funders.awards]]
        name = "MRC123"
        recipients = ["alice-exemplar", "bob-exemplar"]
    [[params.funders.awards]]
        name = "MRC456"
        recipients = ["alice-exemplar", "bob-exemplar"]

[[params.funders]]
    name   = "National Institutes of Health"
    url    = "http://www.nih.gov/"
    sameAs = "http://doi.org/10.13039/100000002"
    [[params.funders.awards]]
        name = "NIH123"
        recipients = ["alice-exemplar"]

[[params.contributions]]
    name = "Methodology"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Methodology"
    contributors = [ "alice-exemplar", "bob-exemplar" ]

[[params.contributions]]
    name = "Investigation"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Investigation"
    contributors = [ "alice-exemplar", "bob-exemplar" ]

[[params.contributions]]
    name = "Software"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Software"
    contributors = [ "bob-exemplar" ]

[[params.contributions]]
    name = "Writing - original draft"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_original_draft"
    contributors = [ "alice-exemplar" ]

[[params.contributions]]
    name = "Writing - review & editing"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_review_%26_editing"
    contributors = [ "bob-exemplar" ]

